// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"gorm.io/gorm"
	friend3 "minichat/internal/handler/friend"
	friend_apply3 "minichat/internal/handler/friend_apply"
	group3 "minichat/internal/handler/group"
	user3 "minichat/internal/handler/user"
	"minichat/internal/repo/friend"
	"minichat/internal/repo/friend_apply"
	"minichat/internal/repo/group"
	"minichat/internal/repo/group_member"
	"minichat/internal/repo/user"
	friend2 "minichat/internal/service/friend"
	friend_apply2 "minichat/internal/service/friend_apply"
	group2 "minichat/internal/service/group"
	user2 "minichat/internal/service/user"
)

// Injectors from wire.go:

func InitializeApp(database *gorm.DB) (*HandlerProvider, error) {
	userRepo := user.NewUserRepo(database)
	appConfig := provideAppConfig()
	ossInterface, err := ProvideOSS(appConfig)
	if err != nil {
		return nil, err
	}
	userService := user2.NewUserService(userRepo, ossInterface)
	userHandler := user3.NewUserHandler(userService)
	friendApplyRepo := friend_apply.NewFriendApplyRepo(database)
	friendRepo := friend.NewFriendRepo(database)
	friendApplyService := friend_apply2.NewFriendApplyService(friendApplyRepo, friendRepo, userRepo)
	friendApplyHandler := friend_apply3.NewUserHandler(friendApplyService)
	friendService := friend2.NewFriendService(friendRepo, userRepo)
	friendHandler := friend3.NewFriendHandler(friendService)
	groupRepo := group.NewGroupRepo(database)
	groupMemberRepoInterface := group_member.NewGroupMemberRepo(database)
	groupServiceInterface := group2.NewGroupService(groupRepo, groupMemberRepoInterface)
	groupHandler := group3.NewGroupHandler(groupServiceInterface)
	handlerProvider := &HandlerProvider{
		UserHandler:        userHandler,
		FriendApplyHandler: friendApplyHandler,
		FriendHandler:      friendHandler,
		GroupHandler:       groupHandler,
	}
	return handlerProvider, nil
}

// wire.go:

var UserSet = wire.NewSet(

	provideAppConfig,
	ProvideOSS, user.NewUserRepo, wire.Bind(new(user.UserRepoInterface), new(*user.UserRepo)), user2.NewUserService, wire.Bind(new(user2.UserServiceInterface), new(*user2.UserService)), user3.NewUserHandler,
)

var FriendSet = wire.NewSet(friend.NewFriendRepo, wire.Bind(new(friend.FriendRepoInterface), new(*friend.FriendRepo)), friend2.NewFriendService, wire.Bind(new(friend2.FriendServiceInterface), new(*friend2.FriendService)), friend3.NewFriendHandler)

var FriendApplySet = wire.NewSet(friend_apply.NewFriendApplyRepo, wire.Bind(new(friend_apply.FriendApplyRepoInterface), new(*friend_apply.FriendApplyRepo)), friend_apply2.NewFriendApplyService, wire.Bind(new(friend_apply2.FriendApplyServiceInterface), new(*friend_apply2.FriendApplyService)), friend_apply3.NewUserHandler)

var GroupSet = wire.NewSet(group.NewGroupRepo, wire.Bind(new(group.GroupRepoInterface), new(*group.GroupRepo)), group2.NewGroupService, group3.NewGroupHandler)

var GroupMemberSet = wire.NewSet(group_member.NewGroupMemberRepo)

var HandlerProviderSet = wire.NewSet(
	UserSet,
	FriendSet,
	FriendApplySet,
	GroupSet,
	GroupMemberSet, wire.Struct(new(HandlerProvider), "*"),
)
