// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gorm.io/gorm"
	friend3 "minichat/internal/handler/friend"
	friend_apply3 "minichat/internal/handler/friend_apply"
	user3 "minichat/internal/handler/user"
	"minichat/internal/repo/friend"
	"minichat/internal/repo/friend_apply"
	"minichat/internal/repo/user"
	friend2 "minichat/internal/service/friend"
	friend_apply2 "minichat/internal/service/friend_apply"
	user2 "minichat/internal/service/user"
)

// Injectors from wire.go:

func InitializeApp(database *gorm.DB) (*HandlerProvider, error) {
	userRepoInterface := user.NewUserRepo(database)
	appConfig := provideAppConfig()
	ossInterface, err := ProvideOSS(appConfig)
	if err != nil {
		return nil, err
	}
	userServiceInterface := user2.NewUserService(userRepoInterface, ossInterface)
	userHandler := user3.NewUserHandler(userServiceInterface)
	friendApplyRepoInterface := friend_apply.NewFriendApplyRepo(database)
	friendRepoInterface := friend.NewFriendRepo(database)
	friendApplyServiceInterface := friend_apply2.NewFriendApplyService(friendApplyRepoInterface, friendRepoInterface, userRepoInterface)
	friendApplyHandler := friend_apply3.NewUserHandler(friendApplyServiceInterface)
	friendServiceInterface := friend2.NewFriendService(friendRepoInterface, userRepoInterface)
	friendHandler := friend3.NewFriendHandler(friendServiceInterface)
	handlerProvider := &HandlerProvider{
		UserHandler:        userHandler,
		FriendApplyHandler: friendApplyHandler,
		FriendHandler:      friendHandler,
	}
	return handlerProvider, nil
}
